DP-21928-test-wte-playground-git-repo
nhsengland/WTE-Playground pull request #5
Opened 2024-04-24 10:00 UTC by AliceThompsonNHSE

2024-04-24 10:02 UTC, AnthonyBaneNHSE requested changes
Please see the requested change.

2024-04-24 10:02 UTC, AnthonyBaneNHSE commented on scripts/test_python.py
> +print('Hello World') #this is a test
This is how a review in-line looks and what I was getting at in the call. So I would say something like:

Make sure to remove comments that are not needed.

2024-04-24 11:37 UTC, AliceThompsonNHSE reviewed
Thanks Anthony. Are you saying you would like me to remove the superfluous comment we added?

2024-04-24 13:09 UTC, AnthonyBaneNHSE commented on scripts/test_python.py
> +print('Hello World') #this is a test
@AliceThompsonNHSE when you fix the suggested/required changes and let me know (i.e. delete the comment), I can then review the changes. If this changes are correct I will make this as resolved

2024-04-24 14:13 UTC, AliceThompsonNHSE commented on scripts/test_python.py
> +print('Hello World') #this is a test
I just deleted the comment and committed the change. Thanks.

2024-04-30 07:00 UTC, AnthonyBaneNHSE commented
Closing the PR as we don't actually want to add this to the repo. Make sure you delete your local and origin branches @AliceThompsonNHSE

2024-04-30 07:00 UTC, closed without merging